#!/bin/bash
set -euo pipefail

cd /home/mchen/FiRe-OPD

# srun/sbatch should control visible logical GPU ids. Outside Slurm,
# default to physical GPUs 1-4 to match the local interactive convention.
if [ -n "${SLURM_JOB_ID:-}" ]; then
  export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
else
  export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-1,2,3,4}"
fi

ROLLOUT_N="${ROLLOUT_N:-1}" \
LENGTH_PENALTY_COEF="${LENGTH_PENALTY_COEF:-0.05}" \
LENGTH_PENALTY_TYPE="${LENGTH_PENALTY_TYPE:-log_length_teacher_confidence}" \
LENGTH_PENALTY_GATE="${LENGTH_PENALTY_GATE:-correct}" \
LENGTH_CORRECT_REWARD_THRESHOLD="${LENGTH_CORRECT_REWARD_THRESHOLD:-0.5}" \
LENGTH_TEACHER_REJECT_PERCENTILE="${LENGTH_TEACHER_REJECT_PERCENTILE:-20.0}" \
LENGTH_CONFIDENCE_TEMPERATURE="${LENGTH_CONFIDENCE_TEMPERATURE:-0.1}" \
CANDIDATE_SELECTION_ENABLED="${CANDIDATE_SELECTION_ENABLED:-True}" \
CANDIDATE_SELECTION_METHOD="${CANDIDATE_SELECTION_METHOD:-quality_gated_correct_compression}" \
CANDIDATE_SELECTION_KEEP_PER_UID="${CANDIDATE_SELECTION_KEEP_PER_UID:-1}" \
CANDIDATE_SELECTION_CORRECT_REWARD_THRESHOLD="${CANDIDATE_SELECTION_CORRECT_REWARD_THRESHOLD:-0.5}" \
CANDIDATE_SELECTION_TEACHER_REJECT_PERCENTILE="${CANDIDATE_SELECTION_TEACHER_REJECT_PERCENTILE:-20.0}" \
CANDIDATE_SELECTION_DROP_REJECTED_NO_CORRECT="${CANDIDATE_SELECTION_DROP_REJECTED_NO_CORRECT:-True}" \
bash verl/examples/fire_opd/run_opd_strong_to_weak_lengthaware_correctcompress_teacher30b.sh
